In [2]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import re
import pandas as pd

In [3]:
dataset = pd.read_csv("tripadvisor-hotel-reviews.csv")
dataset['lowercased_review'] = dataset['Review'].str.lower()
dataset.head()
# dataset['Review'][0]

,Review,Rating,lowercased_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

Remove Stopwords

In [4]:
en_stopwords = stopwords.words('english')

dataset['no_stopwords'] = dataset['lowercased_review'].apply(lambda x: " ".join([word for word in x.split() if word not in en_stopwords]))

dataset.head()

,Review,Rating,lowercased_review,no_stopwords
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

Removing Punctuations

In [5]:
dataset['reviews_no_punct'] = dataset.apply(lambda x: re.sub(r"[*]", " star", x['no_stopwords']), axis=1)
dataset['reviews_no_punct'] = dataset.apply(lambda x: re.sub(r"[^\w\s]", "", x['reviews_no_punct']), axis=1)
dataset.head()

,Review,Rating,lowercased_review,no_stopwords,reviews_no_punct
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4 star experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...

Tokenization

In [6]:
dataset['tokenized_review'] = dataset.apply(lambda x: word_tokenize(x['reviews_no_punct']), axis=1)
dataset.head()

,Review,Rating,lowercased_review,no_stopwords,reviews_no_punct,tokenized_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4 star experience hotel monaco seat...,"[nice, rooms, 4, star, experience, hotel, mona..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game..."

Stemming & Lemmatization

In [7]:
ps = PorterStemmer()
dataset['stemmed_review'] = dataset['tokenized_review'].apply(lambda tokens: [ps.stem(token) for token in tokens])

In [8]:
lem = WordNetLemmatizer()
dataset['lemmatized_review'] = dataset['tokenized_review'].apply(lambda tokens: [lem.lemmatize(token) for token in tokens])
dataset.head()

,Review,Rating,lowercased_review,no_stopwords,reviews_no_punct,tokenized_review,stemmed_review,lemmatized_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s...","[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi...","[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4 star experience hotel monaco seat...,"[nice, rooms, 4, star, experience, hotel, mona...","[nice, room, 4, star, experi, hotel, monaco, s...","[nice, room, 4, star, experience, hotel, monac..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona...","[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

N-grams

In [15]:
lematized_list = sum(dataset['lemmatized_review'], [])

unigrams = pd.Series(nltk.ngrams(lematized_list, 1)).value_counts()
print(unigrams.sort_values())

(25th,)         1
(rudely,)       1
(stocked,)      1
(stopped,)      1
(switch,)       1
             ...
(staff,)       90
(stay,)        95
(great,)      126
(room,)       275
(hotel,)      292
Name: count, Length: 2588, dtype: int64

In [17]:
bigrams = pd.Series(nltk.ngrams(lematized_list, 2)).value_counts()
print(bigrams)

(great, location)           24
(space, needle)             21
(hotel, monaco)             16
(staff, friendly)           13
(great, view)               12
                            ..
(hotel, dissapointment)      1
(unfortunately, warwick)     1
(agency, unfortunately)      1
(travel, agency)             1
(food, raffle)               1
Name: count, Length: 8184, dtype: int64