Parts Of Speech(POS) Tagging

In [124]:
import spacy
import pandas as pd
import re
from nltk.corpus import stopwords

In [125]:
nlp = spacy.load('en_core_web_sm')
emma_ja = "The event had every promise of happiness for her friend. Mr. Weston was a man of unexceptionable character,\
 easy fortune, suitable age, and pleasant manners; and there was some satisfaction in considering with what self-denying,\
 generous friendship she had always wished and promoted the match; but it was a black morning’s work for her.\
 The want of Miss Taylor would be felt every hour of every day. She recalled her past kindness—the kindness,\
 the affection of sixteen years—how she had taught and how she had played with her from five years old—how\
 she had devoted all her powers to attach and amuse her in health—and how nursed her through the various illnesses of childhood.\
 A large debt of gratitude was owing here; but the intercourse of the last seven years, the equal footing and perfect unreserve\
 which had soon followed Isabella’s marriage, on their being left to each other, was yet a dearer, tenderer recollection.\
 She had been a friend and companion such as few possessed: intelligent, well-informed, useful, gentle, knowing all the ways of the family,\
 interested in all its concerns, and peculiarly interested in herself, in every pleasure,\
 every scheme of hers—one to whom she could speak every thought as it arose,\
 and who had such an affection for her as could never find fault."

In [126]:
emma_ja_lowercased = emma_ja.lower()

en_stopwords = stopwords.words('english')
emma_ja_no_stopwords = " ".join([word for word in emma_ja_lowercased.split() if word not in en_stopwords])

In [127]:
final_emma_ja = re.sub(r"[^\w\s]", "", emma_ja_no_stopwords)
print(final_emma_ja.__len__())

852

In [128]:
spacy_doc = nlp(final_emma_ja)

pos_dic = [{"Token":token.text, "Parts Of Speech":token.pos_} for token in spacy_doc]

pos_df = pd.DataFrame(pos_dic)
pos_df.head()

       Token Parts Of Speech
0      event            NOUN
1      every             DET
2    promise            NOUN
3  happiness            NOUN
4     friend            NOUN

In [129]:
pos_df.head(15)

              Token Parts Of Speech
0             event            NOUN
1             every             DET
2           promise            NOUN
3         happiness            NOUN
4            friend            NOUN
5                mr           PROPN
6            weston           PROPN
7               man           PROPN
8   unexceptionable             ADJ
9         character            NOUN
10             easy             ADJ
11          fortune            NOUN
12         suitable             ADJ
13              age            NOUN
14         pleasant             ADJ

In [130]:
pos_df_counts = pos_df.groupby('Parts Of Speech')['Token'].size().sort_values(ascending=False)
print(pos_df_counts)

Parts Of Speech
NOUN     37
VERB     24
ADJ      19
PROPN     9
ADV       7
DET       6
AUX       3
NUM       3
PRON      2
ADP       1
CCONJ     1
Name: Token, dtype: int64

In [131]:
nouns = pos_df[pos_df['Parts Of Speech'] == "NOUN"]
print(nouns['Token'].value_counts())

Token
years           2
friend          2
affection       2
event           1
companion       1
gratitude       1
intercourse     1
unreserve       1
marriage        1
ways            1
illnesses       1
family          1
concerns        1
pleasure        1
scheme          1
hersone         1
thought         1
debt            1
powers          1
healthand       1
promise         1
kindness        1
day             1
hour            1
mornings        1
match           1
friendship      1
satisfaction    1
manners         1
age             1
fortune         1
character       1
happiness       1
fault           1
Name: count, dtype: int64

Name Entity Recognition (NER)

In [132]:
import spacy
from spacy import displacy
from spacy import tokenizer
from IPython.display import HTML, display
import re

In [133]:
nlp = spacy.load('en_core_web_sm')

In [134]:
google_text = "Google was founded on September 4, 1998, by American computer scientists Larry Page and Sergey Brin. Together, they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."
print(google_text)

Google was founded on September 4, 1998, by American computer scientists Larry Page and Sergey Brin. Together, they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.

In [135]:
spacy_doc_2 = nlp(google_text)

google_text_tokens = [(word.text, word.label_ ) for word in spacy_doc_2.ents]

print(google_text_tokens)

[('Google', 'ORG'), ('September 4, 1998', 'DATE'), ('American', 'NORP'), ('Larry Page', 'PERSON'), ('Sergey Brin', 'PERSON'), ('about 14%', 'PERCENT'), ('56%', 'PERCENT'), ('IPO', 'ORG'), ('2004', 'DATE'), ('2015', 'DATE'), ('Google', 'ORG'), ('Alphabet Inc.', 'ORG'), ('Alphabet', 'ORG'), ('Alphabet', 'ORG'), ('Sundar Pichai', 'PERSON'), ('Google', 'ORG'), ('October 24, 2015', 'DATE'), ('Larry Page', 'PERSON'), ('Alphabet', 'GPE'), ('December 3, 2019', 'DATE'), ('Pichai', 'PERSON'), ('Alphabet', 'GPE')]

In [136]:
html = displacy.render(spacy_doc_2, style='ent', jupyter=False)
display(HTML(html))

In [138]:
google_text_2 = google_text.lower()
google_text_final = re.sub(r"[^\w\s]", "", google_text_2)

spacy_clean = nlp(google_text_final)

google_clean_tokens = [(word.text, word.label_) for word in spacy_clean.ents]
print(google_text_final)

google was founded on september 4 1998 by american computer scientists larry page and sergey brin together they own about 14 of its publicly listed shares and control 56 of its stockholder voting power through supervoting stock the company went public via an initial public offering ipo in 2004 in 2015 google was reorganized as a wholly owned subsidiary of alphabet inc google is alphabets largest subsidiary and is a holding company for alphabets internet properties and interests sundar pichai was appointed ceo of google on october 24 2015 replacing larry page who became the ceo of alphabet on december 3 2019 pichai also became the ceo of alphabet

In [140]:
html2 = displacy.render(spacy_clean, style='ent', jupyter=False)
display(HTML(html2))